# Custom Language File for Launcher Customizer

[ejs.app]
title = "Operation-Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Shirou-Dev/Operation-Launcher"
mediaTwitterURL = ""
mediaInstagramURL = ""
mediaYouTubeURL = "https://www.youtube.com/@rebootproject"
mediaDiscordURL = "https://discord.gg/qkWtutEP7J"

[ejs.settings]
sourceGithubLink = "https://github.com/Shirou-Dev/Operation-Launcher"
supportLink = ""

[ejs.welcome]
welcomeHeader = "ยินดีต้อนรับเข้าสู่ Operation Project"
welcomeDescription = "Operation-Launcher พัฒนาโดย OP-Developer"
welcomeDescCTA = "( Credit By Helios-Launcher )"
